#!name=闲鱼开屏广告
#!desc=拦截闲鱼启动页广告和通用广告曝光请求
#!author=ddgksf2013 / sbc2fjbdn5-prog
#!homepage=https://github.com/sbc2fjbdn5-prog/yfamilys-qx-mirror
#!icon=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/App_Store.png

# 当前接口规则参考 ddgksf2013/Rewrite 的 GoofishAds.conf，精简为开屏广告专用版本。

hostname = acs.m.goofish.com, g-acs.m.goofish.com

# 开屏广告
^https?:\/\/(g-)?acs\.m\.goofish\.com\/gw\/mtop.*splash\.ads url reject-200

# 通用广告曝光
^https?:\/\/(g-)?acs\.m\.goofish\.com\/gw\/mtop\.idle\.ad\.expose url reject-200
